import type { Metadata } from "next";
import "./globals.css"
import { ThemeProvider } from "@/components/theme"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <body className="bg-primary-50 dark:bg-neutral-900">{children}</body>
    </ThemeProvider>
  );
}
